k rolling updates

diff --git a/resources/04app_life_cycle_mgmt b/resources/04app_life_cycle_mgmt
--- a/resources/04app_life_cycle_mgmt
+++ b/resources/04app_life_cycle_mgmt
@@ -13,11 +13,31 @@ k run nginx --image=nginx
 > kubectl create –f deployment-definition.yml
 > kubectl get deployments
 > kubectl apply –f deployment-definition.yml
-> kubectl set image deployment/myapp-deployment nginx=nginx:1.9.1 > kubectl rollout status deployment/myapp-deployment
+> kubectl set image deployment/myapp-deployment nginx=nginx:1.9.1 
+> kubectl rollout status deployment/myapp-deployment
 > kubectl rollout history deployment/myapp-deployment
 > kubectl rollout undo deployment/myapp-deployment
 
+k set image deploy frontend simple-webapp=kodekloud/webapp-color:v2
+k set image deploy frontend simple-webapp=kodekloud/webapp-color:v3
 
+controlplane ~ ➜  cat curl-test.sh 
+for i in {1..35}; do
+   kubectl exec --namespace=kube-public curl -- sh -c 'test=`wget -qO- -T 2  http://webapp-service.default.svc.cluster.local:8080/info 2>&1` && echo "$test OK" || echo "Failed"';
+   echo ""
+done
+
+controlplane ~ ➜  cat curl-pod.yaml 
+apiVersion: v1 
+kind: Pod
+metadata:
+  name: curl
+  namespace: kube-public 
+spec:
+  containers:
+  - image: byrnedo/alpine-curl:latest
+    name: alpine-curl
+    command: ["sleep", "5000"]
 
 
 
